version: '2'

services:

  telegram:
    build: ./telegram
    depends_on:
      - redis
      - instagram
      - caption
      - hashtag
    restart: on-failure
    environment:
      TELEGRAM_REDIS_ADDR: redis:6379
    env_file:
      - .env

  instagram:
    build: ./instagram
    depends_on:
      - redis
      - caption
      - hashtag
    restart: on-failure
    environment:
      WORKER_REDIS_ADDR: redis:6379
    env_file:
      - .env

  caption:
    build: ./caption
    depends_on:
      - redis
    restart: on-failure
    environment:
      WORKER_REDIS_ADDR: redis:6379
    env_file:
      - .env

  hashtag:
    build: ./hashtag
    depends_on:
      - redis
    restart: on-failure
    environment:
      WORKER_REDIS_ADDR: redis:6379
      GOOGLE_APPLICATION_CREDENTIALS: key.json

  redis:
    image: redis:3.2.11
    restart: on-failure